apiVersion: v1
kind: Pod
metadata:
  name: pod-resources
  namespace: dev2025
spec:
  containers:
  - name: nginx
    image: nginx:1.71.1
    resources:   #资源配额
      limits:    #资源限制上限
        cpu: "2" #CPU限制，单位是core数
        memory: "10Gi" #内存限制
      requests: #请求资源(下限）
        cpu: "1" #CPU 限制，单位是core 数 ，CPU 核心至少有一个，Pod 才可以成功启动
        memory: "10Mi" #内存限制，内存至少为10M Pod 才可以成功启动



